#!/bin/bash

ACTIVE_WORKSPACE=$(hyprctl monitors | grep -C 5 "focused: yes" | grep active | awk '{print $3}')
PREV_WORKSPACE=$(expr $ACTIVE_WORKSPACE - 1)

if (( $PREV_WORKSPACE == 0 )); then
	PREV_WORKSPACE==8
fi

if (($PREV_WORKSPACE == 9)); then
	PREV_WORKSPACE=18
fi

hyprctl dispatch workspace $PREV_WORKSPACE
